### ISSUE TITLE
Program crashes when I try to use VisualVM to profile it.

### ISSUE THREAD

**Issue by Angular-Angel** [oracle/visualvm#377]
**Describe the bug**
When I run my application and start profiling it with Visualvm while it's on it's menu screen, it works okay, but I get a bunch of warnings in console:

`OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Profiler Agent: Waiting for connection on port 5140 (Protocol version: 20)
Profiler Agent: Established connection with the tool
*** Profiler engine warning: Cannot use ClassLoader.findLoadedClass() and/or ClassLoader.findBootstrapClass() in ClassLoaderManager`

If I then try and launch the actual game, the game crashes:

`Profiler Agent: Local accelerated session
*** Profiler engine warning: class jdk.internal.reflect.GeneratedMethodAccessor49 loaded by *** Profiler Agent Communication Thread
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.lang.StackWalker$StackFrame.getFileName()" is null`

 VisualVM continues just fine. I was able to use VisualVM to profile the game before - but that was when I was building it with Maven. I recently switched to building it with Gradle. The game includes Lombok - I think that may be the issue, that lombok is changing things during runtime, or something? Not sure why this happens with Gradle but didn't happen with Maven.

**To Reproduce**
1. Build the maven branch of: https://gitlab.com/AngularAngel/devilutil
2. Build the gradle branch of: https://gitlab.com/AngularAngel/omnicraft,
3. Run the game
4. Run VisualVM and start profiling the game.
5. Click 'Local Game' and then 'Play'

**Expected behavior**
The game continues running and I am able to profile it.

**Desktop (please complete the following information):**
 - OS: Xubuntu 20.04
 - Graal 17
 - Lombok Version 1.18.22

**Comment by thurka** [comment]
Can you post the stack trace for above NPE: `java.lang.NullPointerException: Cannot invoke "String.equals(Object)"`?

**Comment by Angular-Angel** [comment]
Here you go!

`java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.lang.StackWalker$StackFrame.getFileName()" is null
	at org.lwjgl.system.StackWalkUtil.isSameMethod(StackWalkUtil.java:44)
	at org.lwjgl.system.StackWalkUtil.isSameMethod(StackWalkUtil.java:38)
	at org.lwjgl.system.StackWalkUtil.lambda$stackWalkCheckPop$4(StackWalkUtil.java:72)
	at java.base/java.lang.StackStreamFactory$StackFrameTraverser.consumeFrames(StackStreamFactory.java:534)
	at java.base/java.lang.StackStreamFactory$AbstractStackWalker.doStackWalk(StackStreamFactory.java:306)
	at java.base/java.lang.StackStreamFactory$AbstractStackWalker.callStackWalk(Native Method)
	at java.base/java.lang.StackStreamFactory$AbstractStackWalker.beginStackWalk(StackStreamFactory.java:370)
	at java.base/java.lang.StackStreamFactory$AbstractStackWalker.walk(StackStreamFactory.java:243)
	at java.base/java.lang.StackWalker.walk(StackWalker.java:498)
	at org.lwjgl.system.StackWalkUtil.stackWalkCheckPop(StackWalkUtil.java:62)
	at org.lwjgl.system.MemoryStack$DebugMemoryStack.pop(MemoryStack.java:200)
	at org.lwjgl.system.MemoryStack.close(MemoryStack.java:168)
	at com.samrj.devil.game.Mouse.getPos(Unknown Source)
	at net.angle.omnicraft.client.world.entities.ClientPlayer.<init>(ClientPlayer.java:54)
	at net.angle.omnicraft.client.world.entities.ClientPlayer.<init>(ClientPlayer.java:42)
	at net.angle.omnicraft.client.GameScreen.<init>(GameScreen.java:62)
	at net.angle.omnicraft.client.DebugClient.startSinglePlayerGame(DebugClient.java:157)
	at net.angle.omnicraft.client.WorldSelectScreen.lambda$createMenuWindow$0(WorldSelectScreen.java:45)
	at com.samrj.devil.gui.Button.activate(Button.java:87)
	at com.samrj.devil.gui.DUI.mouseButton(Unknown Source)
	at net.angle.omnicraft.client.MenuScreen.mouseButton(MenuScreen.java:65)
	at net.angle.omnicraft.client.DebugClient.mouseButton(DebugClient.java:89)
	at com.samrj.devil.game.Game.lambda$run$3(Unknown Source)
	at com.samrj.devil.game.Mouse.button(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(Unknown Source)
	at com.samrj.devil.game.Game.run(Unknown Source)
	at net.angle.omnicraft.client.Client.run(Unknown Source)
	at net.angle.omnicraft.client.DebugClient.main(Unknown Source)`

**Comment by Angular-Angel** [comment]
Huh, it looks like the code it's choking on is from DevilUtil. So, maybe the issue is gradle not bundling the dependencies at runtime in a way VisualVM can work with? :/

**Comment by thurka** [comment]
I think the problem is in `org.lwjgl.system.StackWalkUtil.isSameMethod(StackWalkUtil.java:44)`.  `StackFrame.getFileName()` can return null if the information is not available. See its [Javadoc](https://docs.oracle.com/javase/10/docs/api/java/lang/StackWalker.StackFrame.html#getFileName()).

**Comment by Angular-Angel** [comment]
But why is this only a problem now? I can run the project with maven and use VisualVM on it just fine. But when I use gradle, suddenly I have a problem. :/

**Comment by Angular-Angel** [comment]
Fixed my problem. Apparently, if your project includes Lombok, you need to add a plugin for it:

```id "io.freefair.lombok" version "6.3.0"```, from: https://plugins.gradle.org/plugin/io.freefair.lombok

instead of directly adding it as a dependency and an annotation processor:
```
    compileOnly 'org.projectlombok:lombok:1.18.22'
    annotationProcessor 'org.projectlombok:lombok:1.18.22'
```
If you do it the second way, your project will still build and run, but it will crash if you try and profile it.

**Comment by thurka** [comment]
> Fixed my problem.

Ok, I still think that the bug at `org.lwjgl.system.StackWalkUtil.isSameMethod()` should be fixed.

**Comment by Angular-Angel** [comment]
No, wait - It still crashes, but only if start profiling before starting the main game. If you start the main game and then profile, it doesn't crash. Not sure if that's how it was before, or not. :/

**Comment by thurka** [comment]
> No, wait - It still crashes

Well, you need to specify what do you mean by 'crash' and provide some logs from the crash. Currently you reported only the NPE from StackWalkUtil.isSameMethod(), which was solved.

**Comment by Angular-Angel** [comment]
No, that bug was not solved. The people from LWJGL say that it will be in an upcoming release, though.
